# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_auto_20190411_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalresultadoheader',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='resultadoheader',
            name='documentos',
        ),
        migrations.AddField(
            model_name='resultadoheader',
            name='documentos',
            field=models.ManyToManyField(to='FrontEnd.Documento'),
        ),
    ]
