# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_auto_20190413_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='identificador',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcaso',
            name='identificador',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
