# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0004_auto_20190415_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='modelo',
            field=models.CharField(choices=[('ECON', 'Económico'), ('DROG', 'Drogas')], default='DROG', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcaso',
            name='modelo',
            field=models.CharField(choices=[('ECON', 'Económico'), ('DROG', 'Drogas')], default='DROG', max_length=10),
            preserve_default=False,
        ),
    ]
