# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0006_auto_20190430_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='modelo',
            field=models.CharField(choices=[('UFED', 'WhatsApp UFED'), ('OTROS', 'Archivos comunes')], default=('UFED', 'WhatsApp UFED'), max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='modelo',
            field=models.CharField(choices=[('UFED', 'WhatsApp UFED'), ('OTROS', 'Archivos comunes')], default=('UFED', 'WhatsApp UFED'), max_length=20),
        ),
        migrations.AlterField(
            model_name='caso',
            name='modelo',
            field=models.CharField(choices=[('DRUG', 'Drogas'), ('ECON', 'Económico')], default=('DRUG', 'Drogas'), max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcaso',
            name='modelo',
            field=models.CharField(choices=[('DRUG', 'Drogas'), ('ECON', 'Económico')], default=('DRUG', 'Drogas'), max_length=10),
        ),
    ]
