# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-13 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0007_auto_20190613_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='modelo',
            new_name='tipo_archivo',
        ),
        migrations.RenameField(
            model_name='historicaldocumento',
            old_name='modelo',
            new_name='tipo_archivo',
        ),
    ]
