# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-24 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FrontEnd', '0008_auto_20190613_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('eliminado', models.BooleanField()),
                ('finalizado_correcto', models.BooleanField()),
                ('finalizado_incorrecto', models.BooleanField()),
                ('modelo', models.CharField(choices=[('DRUG', 'Drogas'), ('ECON', 'Económico')], default=('DRUG', 'Drogas'), max_length=10)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_investigacion', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='HistoricalCaso',
            new_name='HistoricalInvestigacion',
        ),
        migrations.RenameModel(
            old_name='NotaCaso',
            new_name='NotaInvestigacion',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='historicalinvestigacion',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical investigacion'},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='historicalinforme',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='historicalmensaje',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='historicalresultadoheader',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='resultadoheader',
            name='caso',
        ),
        migrations.AlterField(
            model_name='notainvestigacion',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.Investigacion'),
        ),
        migrations.DeleteModel(
            name='Caso',
        ),
        migrations.AddField(
            model_name='documento',
            name='investigacion',
            field=models.ManyToManyField(blank=True, to='FrontEnd.Investigacion'),
        ),
        migrations.AddField(
            model_name='historicalinforme',
            name='investigacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FrontEnd.Investigacion'),
        ),
        migrations.AddField(
            model_name='historicalmensaje',
            name='investigacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FrontEnd.Investigacion'),
        ),
        migrations.AddField(
            model_name='historicalresultadoheader',
            name='investigacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='FrontEnd.Investigacion'),
        ),
        migrations.AddField(
            model_name='informe',
            name='investigacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.Investigacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='investigacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.Investigacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoheader',
            name='investigacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.Investigacion'),
            preserve_default=False,
        ),
    ]
