# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-30 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0009_auto_20190624_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=28)),
                ('patrón', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
            ],
        ),
    ]
