# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-06 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0011_auto_20190701_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='historicaldocumento',
            name='titulo',
        ),
    ]
