# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-06 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0012_auto_20190705_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='descripcion_doc',
        ),
        migrations.RemoveField(
            model_name='historicaldocumento',
            name='descripcion_doc',
        ),
    ]
