# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0013_auto_20190705_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresultadobusqgeneral',
            name='parrafo_ant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalresultadobusqgeneral',
            name='parrafo_next',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalresultadobusqguiada',
            name='parrafo_ant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalresultadobusqguiada',
            name='parrafo_next',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalresultadobusqinteligente',
            name='parrafo_ant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalresultadobusqinteligente',
            name='parrafo_next',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalresultadobusqinteligentetokens',
            name='parrafo_ant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalresultadobusqinteligentetokens',
            name='parrafo_next',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadobusqgeneral',
            name='parrafo_ant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadobusqgeneral',
            name='parrafo_next',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadobusqguiada',
            name='parrafo_ant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadobusqguiada',
            name='parrafo_next',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadobusqinteligente',
            name='parrafo_ant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadobusqinteligente',
            name='parrafo_next',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadobusqinteligentetokens',
            name='parrafo_ant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadobusqinteligentetokens',
            name='parrafo_next',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalresultadobusqinteligentetokens',
            name='parrafo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultadobusqinteligentetokens',
            name='parrafo',
            field=models.TextField(),
        ),
    ]
