# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0014_auto_20190707_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadesdoc',
            name='incorrecta',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalentidadesdoc',
            name='incorrecta',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
