# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0015_auto_20190714_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestigacion',
            name='modelo',
            field=models.CharField(choices=[('DRUG', 'Drogas'), ('ECON', 'Económicos')], default=('DRUG', 'Drogas'), max_length=10),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='modelo',
            field=models.CharField(choices=[('DRUG', 'Drogas'), ('ECON', 'Económicos')], default=('DRUG', 'Drogas'), max_length=10),
        ),
    ]
